# Generated by Django 3.2.4 on 2023-06-30 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facebookURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('url', models.URLField()),
                ('screenshot_image', models.ImageField(upload_to='screenshots/')),
                ('reason_of_reporting', models.TextField()),
                ('specific_cause', models.TextField()),
                ('digital_act', models.TextField()),
                ('imp_person_category', models.CharField(max_length=100)),
                ('priority_category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(default='', max_length=100)),
                ('status_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whoposturl', models.URLField(default='')),
                ('whoscreenshotimage', models.ImageField(default='', upload_to='screenshots/')),
                ('hisposturl', models.URLField(null=True)),
                ('hisscreenshotimage', models.ImageField(null=True, upload_to='screenshots/')),
                ('reasonforreporting', models.TextField(null=True)),
                ('specificcause', models.TextField(null=True)),
                ('violated_law', models.TextField(null=True)),
                ('proposed_action', models.TextField(null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('status_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
    ]
