# Generated by Django 3.2.4 on 2023-06-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_remove_facebookurl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookurl',
            name='status',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
