# Generated by Django 3.2.4 on 2023-06-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_facebookurl_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookurl',
            name='subcategory',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaurl',
            name='status_date',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
