# Generated by Django 3.2.4 on 2023-06-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_auto_20230630_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookurl',
            name='status_date',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
