# Generated by Django 3.2.4 on 2023-06-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0005_alter_facebookurl_status_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookurl',
            name='status_date',
            field=models.CharField(default='30/06/2023', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaurl',
            name='status_date',
            field=models.CharField(default='30/06/2023', max_length=50, null=True),
        ),
    ]
