# Generated by Django 3.2.4 on 2023-07-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0006_auto_20230630_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookurl',
            name='priority_category',
            field=models.CharField(choices=[('Fake Army Accounts', 'Fake Facebook Accounts in the name of the Bangladesh Army'), ('Fake Navy Accounts', 'Fake Facebook Accounts in the name of the Bangladesh Navy'), ('Fake RAB Accounts', 'Fake Facebook Accounts in the name of Rapid Action Battalion'), ('Fake AirForce Accounts', 'Fake Facebook Accounts in the name of the Bangladesh AirForce'), ('Anti-State Accounts', 'Anti-State Facebook Accounts related to Chittagong Hill Tracks'), ('Anti-State Accounts', 'Anti-State Facebook Accounts of Terrorism/Harassment/Religious incitement and others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facebookurl',
            name='status_date',
            field=models.CharField(default='01/07/2023', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediaurl',
            name='status_date',
            field=models.CharField(default='01/07/2023', max_length=50, null=True),
        ),
    ]
