# Generated by Django 3.2.4 on 2023-07-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0007_auto_20230701_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookurl',
            name='priority_category',
            field=models.CharField(choices=[('Fake Facebook Accounts in the name of the Bangladesh Army', 'Fake Facebook Accounts in the name of the Bangladesh Army'), ('Fake Facebook Accounts in the name of the Bangladesh Navy', 'Fake Facebook Accounts in the name of the Bangladesh Navy'), ('Fake Facebook Accounts in the name of Rapid Action Battalion', 'Fake Facebook Accounts in the name of Rapid Action Battalion'), ('Fake Facebook Accounts in the name of the Bangladesh AirForce', 'Fake Facebook Accounts in the name of the Bangladesh AirForce'), ('Anti-State Facebook Accounts related to Chittagong Hill Tracks', 'Anti-State Facebook Accounts related to Chittagong Hill Tracks'), ('Anti-State Facebook Accounts of Terrorism/Harassment/Religious incitement and others', 'Anti-State Facebook Accounts of Terrorism/Harassment/Religious incitement and others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='facebookurl',
            name='subcategory',
            field=models.CharField(choices=[('ID', 'ID'), ('Page', 'Page'), ('Group', 'Group'), ('Links', 'Links')], default='', max_length=50, null=True),
        ),
    ]
